import React, { useState } from 'react';
import { 
  X, 
  Copy, 
  Check, 
  Download, 
  FileText, 
  Code, 
  ShieldCheck, 
  Layers 
} from 'lucide-react';
import { AnalysisResult } from '../types';

interface ReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  analysis: AnalysisResult;
}

export const ReportModal: React.FC<ReportModalProps> = ({
  isOpen,
  onClose,
  analysis,
}) => {
  const [tab, setTab] = useState<'markdown' | 'json'>('markdown');
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const markdownContent = `# CodePulse Audit Report
**Target File**: \`${analysis.filename}\` (${analysis.language})  
**Analyzed At**: ${new Date(analysis.analyzedAt).toUTCString()}  
**Engine**: ${analysis.aiPowered ? 'Gemini 3.8 Flash + Static Trace' : 'Hybrid Static Trace Engine'}

---

## Executive Summary
- **Overall Code Health**: ${analysis.metrics.overallScore} / 100
- **Security Score**: ${analysis.metrics.securityScore} / 100
- **Runtime Performance**: ${analysis.metrics.performanceScore} / 100
- **Maintainability Index**: ${analysis.metrics.maintainabilityScore} / 100
- **Time Complexity**: \`${analysis.metrics.bigOTime}\`
- **Space Complexity**: \`${analysis.metrics.bigOSpace}\`
- **Estimated Latency**: ${analysis.metrics.estimatedLatencyMs} ms
- **Estimated Heap Allocation**: ${analysis.metrics.estimatedMemoryMb} MB

---

## Findings (${analysis.findings.length})
${
  analysis.findings.length === 0
    ? 'No security vulnerabilities or performance anti-patterns detected.'
    : analysis.findings
        .map(
          (f, idx) => `### ${idx + 1}. [${f.severity.toUpperCase()}] ${f.title}
- **Category**: ${f.category}
- **Line**: ${f.line}
- **Runtime Impact**: ${f.impact}
- **Cause**: ${f.description}
- **Remediation**: ${f.recommendation}
${f.suggestedReplacement ? `\`\`\`${analysis.language}\n${f.suggestedReplacement}\n\`\`\`` : ''}
`
        )
        .join('\n')
}

---

## Remediated Code
\`\`\`${analysis.language}
${analysis.remediatedCode}
\`\`\`

*Report generated by CodePulse AI Code Sentinel & Performance Studio.*
`;

  const jsonContent = JSON.stringify(analysis, null, 2);

  const activeContent = tab === 'markdown' ? markdownContent : jsonContent;

  const handleCopy = async () => {
    await navigator.clipboard.writeText(activeContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const ext = tab === 'markdown' ? 'md' : 'json';
    const blob = new Blob([activeContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `codepulse-report-${analysis.filename}.${ext}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="bg-slate-900 border border-slate-800 rounded-lg w-full max-w-3xl max-h-[85vh] flex flex-col shadow-2xl overflow-hidden">
        {/* Modal Header */}
        <div className="px-5 py-3.5 border-b border-slate-800 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <FileText className="w-4 h-4 text-emerald-400" />
            <h3 className="font-semibold text-slate-100 text-sm">
              Code Audit &amp; Performance Report
            </h3>
            <span className="text-xs text-slate-500 font-mono">
              ({analysis.filename})
            </span>
          </div>

          <button
            onClick={onClose}
            className="p-1 text-slate-400 hover:text-slate-200 rounded transition-colors"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Modal Toolbar */}
        <div className="px-5 py-2.5 bg-slate-950/60 border-b border-slate-800 flex items-center justify-between text-xs">
          <div className="flex items-center gap-1 bg-slate-900 p-0.5 rounded border border-slate-800">
            <button
              onClick={() => setTab('markdown')}
              className={`px-3 py-1 rounded transition-colors ${
                tab === 'markdown' ? 'bg-slate-800 text-white font-medium' : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              Markdown (.md)
            </button>
            <button
              onClick={() => setTab('json')}
              className={`px-3 py-1 rounded transition-colors ${
                tab === 'json' ? 'bg-slate-800 text-white font-medium' : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              JSON (.json)
            </button>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="px-3 py-1.5 rounded bg-slate-900 border border-slate-800 text-slate-300 hover:text-white transition-colors flex items-center gap-1.5"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied!' : 'Copy'}</span>
            </button>
            <button
              onClick={handleDownload}
              className="px-3 py-1.5 rounded bg-emerald-600 hover:bg-emerald-500 text-white transition-colors flex items-center gap-1.5 font-medium"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download</span>
            </button>
          </div>
        </div>

        {/* Modal Content */}
        <div className="p-5 flex-1 overflow-auto bg-slate-950 font-mono text-xs text-slate-300 leading-relaxed">
          <pre className="whitespace-pre-wrap">{activeContent}</pre>
        </div>

        {/* Modal Footer */}
        <div className="px-5 py-3 bg-slate-900 border-t border-slate-800 flex items-center justify-between text-xs text-slate-400">
          <span>OWASP &amp; CWE compliant automated report</span>
          <button
            onClick={onClose}
            className="px-4 py-1.5 rounded bg-slate-800 hover:bg-slate-700 text-slate-200 transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
